*** Variables ***
${what needs to be done inputText}     //input[contains(@placeholder,'What needs to be done')]
${issue count}  //span[@class='todo-count']//*[contains(text(),'')]
${item left}  //span[@class='todo-count']/descendant-or-self::span[contains(text(),'item left')]
${all button}   //a[.='All']
${first item}   (//*[@class='todo-list']//label)[1]
${last item}    (//*[@class='todo-list']//label)[last()]
${first unselected remove button}     (//*[@class='todo-list']//button[@class='destroy'])[1]
${last unselected remove button}     (//*[@class='todo-list']//button[@class='destroy'])[last()]
${select all button}    //label[contains(@for,'toggle-all') and text()='Mark all as complete']